version: '3.4'
services:
  proxy:
    image: 'palanaeum/proxy:latest'
    build:
      context: .
    ports:
      - 9000:80
    depends_on:
      - frontend

  frontend:
    image: 'palanaeum/frontend:latest-${ENV:-dev}'
    build:
      context: frontend
      target: ${ENV:-dev}
    volumes:
      - ./frontend:/app
      - frontend_modules:/app/node_modules
    stdin_open: true
    tty: true

  backend:
    image: 'palanaeum:latest'
    build:
      context: .
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  db:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'docker'
      POSTGRES_DB: 'palanaeum'

  redis:
    image: 'redis'

  celery:
    image: 'palanaeum:latest'
    command: 'celery worker -A palanaeum'
    build:
      context: .
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

volumes:
  frontend_modules:
