# Generated by Django 2.0.4 on 2018-07-06 18:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palanaeum', '0002_auto_20180502_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersentrycollection',
            options={'ordering': ('name',), 'verbose_name': 'user_entry_collection', 'verbose_name_plural': 'user_entry_collections'},
        ),
        migrations.AddField(
            model_name='entryversion',
            name='entry_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='entryversion',
            name='paraphrased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryversion',
            name='tags',
            field=models.ManyToManyField(to='palanaeum.Tag'),
        ),
        migrations.AddField(
            model_name='urlsource',
            name='entry_versions',
            field=models.ManyToManyField(related_name='url_sources', to='palanaeum.EntryVersion'),
        ),
        migrations.AlterField(
            model_name='usersentrycollection',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
