# Generated by Django 2.0.7 on 2018-07-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palanaeum', '0005_auto_20180716_1457'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entryversion',
            managers=[
            ],
        ),
    ]
