# Generated by Django 2.1.4 on 2018-12-10 15:01

import datetime

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palanaeum', '0006_auto_20180716_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entryversion',
            options={'default_related_name': 'versions', 'ordering': ('date', '-id'), 'verbose_name': 'entry version', 'verbose_name_plural': 'entries versions'},
        ),
        migrations.AlterModelOptions(
            name='imagesource',
            options={'ordering': ('event', 'name', 'pk'), 'verbose_name': 'image_source', 'verbose_name_plural': 'image_sources'},
        ),
        migrations.AddField(
            model_name='snippet',
            name='optional',
            field=models.BooleanField(default=False, help_text="This snippet shouldn't be transcribed."),
        ),
        migrations.AlterField(
            model_name='entryversion',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this version was created.'),
        ),
        migrations.AlterField(
            model_name='entryversion',
            name='entry_date',
            field=models.DateField(db_index=True, default=datetime.date.today, help_text='The date when the entry happened'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='page_length',
            field=models.IntegerField(default=20, verbose_name='Preferred page length'),
        ),
    ]
