# Generated by Django 2.1.12 on 2019-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palanaeum', '0008_auto_20190511_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryversion',
            name='direct_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entryversion',
            name='reported_by',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
