# Generated by Django 2.1.8 on 2019-08-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('palanaeum', '0008_auto_20190511_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_name', models.CharField(choices=[('REFERS_TO', 'Refers to'), ('REFERRED_BY', 'Referred to by'), ('ANSWERS', 'Answers'), ('ANSWERED_BY', 'Answered by'), ('CORRECTS', 'Corrects'), ('CORRECTED_BY', 'Corrected by'), ('CONTRADICTS', 'Contradicts')], db_index=True, max_length=16)),
                ('note', models.TextField()),
                ('entry_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='palanaeum.EntryVersion')),
                ('target_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_links', to='palanaeum.Entry')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ('entry_version', 'id'),
            },
        ),
    ]
