# Generated by Django 2.2.8 on 2019-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palanaeum', '0009_auto_20190911_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='review_state',
            field=models.CharField(choices=[('N/A', 'not applicable'), ('PENDING', 'pending'), ('APPROVED', 'approved')], default='N/A', max_length=8),
        ),
    ]
