# Generated by Django 3.2.7 on 2021-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palanaeum', '0013_aboutpage_faqentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='faqentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='faqentry',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
