# Generated by Django 3.2.8 on 2021-10-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palanaeum', '0015_auto_20211006_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='searchable',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
