# Generated by Django 4.0.3 on 2022-04-08 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('palanaeum', '0016_alter_entry_searchable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entryversion',
            name='tags',
            field=models.ManyToManyField(to='palanaeum.tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='palanaeum.tag'),
        ),
    ]
